TWIS-33/forgot pw page
Re-boot-Coding-Bootcamp/TwistaGram pull request #10
Opened 2024-03-06 03:48 UTC by hlee0928

# TWIS-33/forgot pw

## Link to Story

https://re-boot.atlassian.net/browse/TWIS-33

## Description

Created forgot password with email input & reset password button

## Screenshot(s) / GIF(s):

<img width="439" alt="Screen Shot 2024-03-05 at 18 53 28" src="https://github.com/Re-boot-Coding-Bootcamp/TwistaGram/assets/158536265/3975280f-67c9-4867-bbb0-b195e3708e0e">

## Type of change

- [ ] Bug fix
- [x] New feature
- [ ] Dependency / Configuration update
- [ ] Documentation update

## Checklist:

- [x ] My code follows the project's style guidelines
- [ ] I have created a Storybook story for my component(s)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-03-06 16:32 UTC, Muradil-Erkin requested changes

2024-03-06 16:32 UTC, Muradil-Erkin commented on src/app/_components/RegistrationForm/ForgotPW/ForgotPW.stories.tsx
> +// More on how to set up stories at: https://storybook.js.org/docs/writing-stories#default-export
all comments can be removed

2024-03-06 16:32 UTC, Muradil-Erkin commented on src/app/_components/RegistrationForm/ForgotPW/ForgotPW.stories.tsx
> +      alert(`Email: ${email} and Password: ${password}`);
you won't need 2 alerts

2024-03-06 16:32 UTC, Muradil-Erkin commented on src/app/_components/RegistrationForm/ForgotPW/ForgotPW.tsx
> +        <Button variant="contained" sx={{p:2}}>Reset Password</Button>
you should have a callback function that's passed in as props that this button onclick hooks up to

2024-03-06 16:32 UTC, Muradil-Erkin commented on src/app/_components/RegistrationForm/ForgotPW/ForgotPW.stories.tsx
> +};
your component don't currently have any props, so these `args` aren't doing anything. 
you also won't need 2 version of stories.

2024-03-08 22:24 UTC, Jack-Vu reviewed
No additional change request then the current ones

2024-03-11 17:37 UTC, lopezmarvin approved these changes
LGTM!

2024-03-11 20:37 UTC, Tsai-Anthony commented
.

2024-03-11 20:41 UTC, Tsai-Anthony submitted a review, later dismissed
lgtm test

2024-03-12 12:58 UTC, Jack-Vu requested changes
Added some comments on your component your component story still needs some work with the actual story and arguments. Instead of just commenting them out have them reflect your component.

2024-03-13 21:54 UTC, Muradil-Erkin approved these changes

2024-03-14 01:20 UTC, manzire approved these changes
QA manzire test ,looks good !
![image](https://github.com/Re-boot-Coding-Bootcamp/TwistaGram/assets/159389986/4f6d1696-1e85-48f8-bd28-fd6fff96e2ca)

2024-03-14 01:20 UTC, laloclau approved these changes
Checked email box and was able to click on the button.
![image](https://github.com/Re-boot-Coding-Bootcamp/TwistaGram/assets/116094020/990ab95d-2513-4964-861c-a10cefbb8663)

2024-03-14 21:53 UTC, merged