TWIS-38/avatar
Re-boot-Coding-Bootcamp/TwistaGram pull request #15
Opened 2024-03-08 14:55 UTC by Jack-Vu

# TWIS-38/avatar

## Link to Story

https://re-boot.atlassian.net/browse/TWIS-38

## Description

Added a stateless avatar component that is has three fixed sizes: small 24x24px, medium 40x40px, and large 56x56px. Component is required to set if it is clickable or not and will handle a onClick call back function if it is able to be clicked. 

## Screenshot(s) / GIF(s):

![image](https://github.com/Re-boot-Coding-Bootcamp/TwistaGram/assets/124454379/5719eba9-fa80-46eb-bbfd-7ab5c5c08774)

![image](https://github.com/Re-boot-Coding-Bootcamp/TwistaGram/assets/124454379/133b23a5-8143-41ed-bd93-5cf05fbe39bc)

![image](https://github.com/Re-boot-Coding-Bootcamp/TwistaGram/assets/124454379/433350ad-fe5c-46a2-bc48-e948af910f68)

![image](https://github.com/Re-boot-Coding-Bootcamp/TwistaGram/assets/124454379/d8278e29-f992-47a6-8186-910e9b6d3c8d)

## Type of change

- [ ] Bug fix
- [x] New feature
- [ ] Dependency / Configuration update
- [ ] Documentation update

## Checklist:

- [x] My code follows the project's style guidelines
- [x] I have created a Storybook story for my component(s)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-03-08 15:40 UTC, javi-lopezz approved these changes
LGTM, small,medium and large are all clickable when "isClickable" is true 

![Screenshot 2024-03-08 at 10 35 21 AM](https://github.com/Re-boot-Coding-Bootcamp/TwistaGram/assets/139653098/29b4375b-f49a-4520-9a45-587cbfb221c3)

2024-03-08 16:10 UTC, KrystalOm reviewed
<img width="1429" alt="Screenshot 2024-03-08 at 11 03 04 AM" src="https://github.com/Re-boot-Coding-Bootcamp/TwistaGram/assets/139653108/0208a4ce-4d31-4521-88cd-3ed74da68c19">
Small, medium, and large are clickable, but I don't get the pop-up window.

2024-03-08 16:29 UTC, Jack-Vu commented
@KrystalOm to view the pop up you'll need to be in the Clickable story under the Avatar. You are currently in the Default which is doesn't handle the onClick function!

2024-03-08 17:01 UTC, Muradil-Erkin requested changes

2024-03-08 17:01 UTC, Muradil-Erkin commented on src/app/_components/Avatar/Avatar.tsx
> +  }
this is fine, but an object mapping might be even better.

2024-03-08 17:01 UTC, Muradil-Erkin commented
@Jack-Vu Also, don't forget to include a `index.ts` to export the component to top level

2024-03-09 02:11 UTC, HuiYangUS approved these changes
> 1. Three sizes (small, medium, large): Matched
> 2. Sizes (24x24, 40x40, 56x56): Matched
> 3. Unclickable (Default Cursor=Arrow): Matched
> 4. Clickable (Cursor=Hand): Matched

* This PR is QA approved.

2024-03-11 19:31 UTC, Muradil-Erkin approved these changes

2024-03-11 20:06 UTC, ShinK8245 approved these changes
LGTM!

2024-03-11 20:06 UTC, merged