comment icon
Re-boot-Coding-Bootcamp/TwistaGram pull request #29
Opened 2024-03-20 20:46 UTC by hlee0928

# TWIS-75/Comment-icon

## Link to Story

https://re-boot.atlassian.net/browse/TWIS-75

## Description

Added a comment icon with tooltip "reply"

## Screenshot(s) / GIF(s):

<img width="270" alt="Screen Shot 2024-03-20 at 16 42 44" src="https://github.com/Re-boot-Coding-Bootcamp/TwistaGram/assets/158536265/fb0f5488-b44f-47bf-b342-c914a279ab38">

## Type of change

- [ ] Bug fix
- [x] New feature
- [ ] Dependency / Configuration update
- [ ] Documentation update

## Checklist:

- [x] My code follows the project's style guidelines
- [x ] I have created a Storybook story for my component(s)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-03-20 21:21 UTC, Jack-Vu requested changes
I see you've exported it in the CommmentIcon index.ts, but make sure to also export it in the _components level index.ts too

2024-03-20 21:21 UTC, Jack-Vu commented on src/app/_components/CommentIcon/CommentIcon.stories.tsx
> +  title: "Common/CommentIcon",
change Title to Components/CommentIcon instead of Common/CommentIcon

2024-03-20 21:21 UTC, Jack-Vu commented on src/app/_components/CommentIcon/CommentIcon.tsx
> +            sx={{ color: blue[300] }}
try using our primary color from the theme for this blue

2024-03-21 21:47 UTC, Jack-Vu requested changes
You'll still need to export this in the root level index.ts under the _component there should be a index.ts file where you will export it there as well

2024-03-21 22:03 UTC, Jack-Vu requested changes
branch has a conflict, so youll need to rebase and resolve the conflict as long as you accept both changes and rebase -- continue then git push -f it should resolve it.

2024-03-21 22:15 UTC, Muradil-Erkin approved these changes

2024-03-21 22:17 UTC, Jack-Vu approved these changes
LGTM!

2024-03-21 22:26 UTC, merged