Twis 35/forgot password confirmation
Re-boot-Coding-Bootcamp/TwistaGram pull request #7
Opened 2024-03-06 00:15 UTC by BaburDilshat

# TWIS-35/forgot password confirmation

## Link to Story

https://re-boot.atlassian.net/browse/TWIS-35?atlOrigin=eyJpIjoiMjNhNGNmZGQzMzRhNGUyMmIxMTYzYmQ2M2JiNDlkY2IiLCJwIjoiaiJ9

## Description

adding a component for reset password confirmation

## Screenshot(s) / GIF(s):

<img width="758" alt="image" src="https://github.com/Re-boot-Coding-Bootcamp/TwistaGram/assets/158536270/e8040bd3-fbc8-48c6-affd-0ec6ad5287e9">

## Type of change

- [ ] Bug fix
- [x] New feature
- [ ] Dependency / Configuration update
- [ ] Documentation update

## Checklist:

- [x] My code follows the project's style guidelines
- [x] I have created a Storybook story for my component(s)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-03-06 16:39 UTC, Muradil-Erkin commented on src/app/_components/ForgotPassword/ForgotPassword.tsx
> +      >
rebase with `dev` to get the theme changes so that here you can just use the default mui button without additional style

2024-03-06 20:54 UTC, Jack-Vu requested changes

2024-03-06 20:54 UTC, Jack-Vu commented on src/app/_components/ForgotPassword/ForgotPassword.stories.tsx
> +// More on writing stories with args: https://storybook.js.org/docs/writing-stories/args
will need need to change these stories to reflect you component

2024-03-06 20:57 UTC, Jack-Vu reviewed
Also maybe being too picky but I think the text for the small paragraph is a bit lighter we may need to come up with some text theme colors

2024-03-10 14:34 UTC, Muradil-Erkin commented on src/app/_components/ForgotPassword/ForgotPassword.stories.tsx
> +    email: { control: "text" },
Your build failure is saying this `email` field doesn't exist in your component props type. 
![image](https://github.com/Re-boot-Coding-Bootcamp/TwistaGram/assets/24844451/47e5cba8-cd02-4c38-a15c-394eb4e8a095)

2024-03-10 14:35 UTC, Muradil-Erkin requested changes

2024-03-10 14:35 UTC, Muradil-Erkin commented on src/app/_components/ForgotPassword/ForgotPassword.tsx
> +interface confirmResetPasswordProps {
Interface should always be Pascal cased.

2024-03-12 20:54 UTC, Muradil-Erkin approved these changes

2024-03-12 21:00 UTC, merged